<br><br><br><br><br><br><br><br><br><br>
<div class="logo">
    <h1><a href="menu.phtml"><img src="assets/img/outras/404.png"/></a></h1>
    <span style="font-family: 'Roboto', sans-serif;"><img src="assets/img/outras/signal.png"/>Oops! Você está em uma pagina que não foi encontrada!</span><br>
    <div align="center">
        <div class="section"></div> <a href="menu" class="waves-effect waves-light btn laranja"><i class="material-icons left">arrow_back</i>Voltar</a>
    </div>
</div>
