<div align="center">
    <div class="section"></div>
    <div class="section"></div>
    <h5 style="font-family: 'Roboto', sans-serif; color: #FFF">Adicionar uma nova questão</h5><br>
    <div class="container">
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">
            <form class="col s12" name="formQuestões" action="cadastrar-pergunta" method="post" autocomplete="off">
                <div class='row'>
                    <div class='col s12'></div>
                </div>
                <div class="input-field col s6"> <input id="enunciado" name="enunciado" type="text" class="validate" style="color:#000" tabindex="1" required> <label for="text">Enunciado<n style="color: #ec1c24"> *</n></label> </div>
                <div class="input-field col s6"> <input id="alt_correta" name="alt_correta" type="text" class="validate" style="color:#000" tabindex="2" required> <label for="text">Alternativa correta<n style="color: #ec1c24"> *</n></label> </div>
                <div class="input-field col s4"> <input id="alt_incorreta_1" name="alt_incorreta_1" type="text" class="validate" style="color:#000" tabindex="3" required> <label for="text">Alternativa incorreta 1<n style="color: #ec1c24"> *</n></label> </div>
                <div class="input-field col s4"> <input id="alt_incorreta_2" name="alt_incorreta_2" type="text" class="validate" style="color:#000" tabindex="4" required> <label for="text">Alternativa incorreta 2<n style="color: #ec1c24"> *</n></label> </div>
                <div class="input-field col s4"> <input id="alt_incorreta_3" name="alt_incorreta_3" type="text" class="validate" style="color:#000" tabindex="5" required> <label for="text">Alternativa incorreta 3<n style="color: #ec1c24"> *</n></label> </div>
                <div class="row">
                    <div class="col s12">
                        <n style="color: #9E9E9E">De qual matéria é essa questão?
                            <n style="color: #ec1c24"> *</n>
                        </n>
                        <select id="materia" name="materia" class="browser-default" style="color: #000; background-color: #f5f5f5" tabindex="5" required> <option value="" disabled selected style="color: #9E9E9E">Escolha uma opção</option> 
                            <?php BuscarMaterias::buscar(); ?> 
                        </select>
                    </div>
                </div>
                <div align="center">
                    <div class='row'><button type='submit' name='btn_login' class="col s12 btn btn-large waves-effect laranja" tabindex="6">Enviar questão</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="container">
    <div align="center">
        <div class="section"></div>
        <h5 style="font-family: 'Roboto', sans-serif; color: #FFF">Remover uma questão</h5><br>
    </div>
    <ul class="collapsible grey" data-collapsible="accordion">
        <?php ListarPerguntas::listar(); ?> </ul>
</div><br>
<div align="center">
    <div class="container"> <a href="professor" class=" s12 btn-floating btn-large waves-effect waves-light laranja"><i class="material-icons">arrow_back</i></a><br><a style="color: #FFF">Voltar</a> </div>
</div><br>
