<div class="container">

    <div class="row">
        <div class="col s12 m12">
            <div class="card-panel laranja" style="">
                <span class="white-text"><h5><a href="menu"><i class="fa fa-users" aria-hidden="true" style="font-size: 1em; color: #fff"></i></a> Criadores do projeto</h5></span>
            </div>
        </div>
    </div>

    <ul class="collection with-header">
        <li class="collection-item"><div><b>Programador</b> - Felipe Novais<a href="https://github.com/FelipeNS" class="secondary-content"><i class="fa fa-github" aria-hidden="true" style="color: #000; font-size: 2em"></i></a></div></li>
        
        <li class="collection-item"><div><b>Programador</b> - Vinnicius Gomes
        <a href="https://github.com/VinniciusGomes" class="secondary-content"><i class="fa fa-github" aria-hidden="true" style="color: #000; font-size: 2em"></i></a></div></li>
        
        <li class="collection-item"><div><b>Professora</b> - Ellen Juliane<a href="" class="secondary-content"><i class="fa fa-graduation-cap" aria-hidden="true" style="color: #FFA500; font-size: 1.5em"></i></a></div></li>
        
        <li class="collection-item"><div><b>Professora</b> - Ariadne Monteiro<a href="" class="secondary-content"><i class="fa fa-graduation-cap" aria-hidden="true" style="color: #FFA500; font-size: 1.5em"></i></a></div></li>
        
        <li class="collection-item"><div><b>Professora</b> - Rafaela Bastos<a href="" class="secondary-content"><i class="fa fa-graduation-cap" aria-hidden="true" style="color: #FFA500; font-size: 1.5em"></i></a></div></li>
        
        <li class="collection-item"><div><b>Professora</b> - Arielli Nely<a href="" class="secondary-content"><i class="fa fa-graduation-cap" aria-hidden="true" style="color: #FFA500; font-size: 1.5em"></i></a></div></li>
      </ul>

    <div align="center"><br>
        <a href="login" class=" s12 btn-floating btn-large waves-effect waves-light laranja"><i class="material-icons">arrow_back</i></a><br>
        <a style="color: #FFF">Voltar</a>
    </div>

</div>