<div class="section"></div>
<div class="container">
    <div class="row">
        <div class="col s12 m12">
            <div class="card-panel laranja" style="">
                <span class="white-text">
                    <h5><a href="professor"><i class="fa fa-user" aria-hidden="true" style="font-size: 1.5em; color: #fff"></i></a> Usuários cadastrados</h5>
                </span>
            </div>
        </div>
    </div>
    <div align="center">
        <div class="section"></div>
    </div>
    <ul class="collapsible grey" data-collapsible="accordion">
        <?php ListarUsuarios::listar(); ?>
    </ul>
    <div align="center"><br>
        <a href="menu" class=" s12 btn-floating btn-large waves-effect waves-light laranja"><i class="material-icons">arrow_back</i></a><br>
        <a style="color: #FFF">Voltar</a>
    </div><br>
</div>
