<div class="section"></div>
<div align="center">
    <div class="container">
        <h3 style=" font-family: 'Roboto', sans-serif; font-weight: 500; font-size: 19px; color: #FFF">Bem vindo ao Quiz</h3>
        <div class="section"></div>
        <h5 style="font-family: 'Roboto', sans-serif; color: #FFF">Para entrar você precisa fazer login</h5><br><br>
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">
            <form class="col s12" name="formLogin" action="acesso" method="post" autocomplete="off">
                <div class='row'>
                    <div class='col s12'></div>
                </div>
                <div class='row'>
                    <div class='input-field col s12'>
                        <input class='validate' type='text' name='nick' id='nick' minlength="5" maxlength="15" style="color:#000" tabindex="1" required>
                        <label for='name'>Seu nick</label>
                    </div>
                </div>
                <div class='row'>
                    <div class='input-field col s12'>
                        <input class='validate' type='password' name='password' id='password' tabindex="2" minlength="5" maxlength="15" style="color:#000" required>
                        <label for='password'>Sua senha</label>
                    </div>
                    <label style='float: right;'>
                        <p class='orange-text' style=" font-family: 'Roboto', sans-serif; font-size: 10px;">Preencha todos os campos</p>
                    </label>
                </div><br>
                <div class="center">
                    <?php if(isset($_GET['e'])){$erro=$_GET['e']; if($erro==1){echo "<label> <b style='font-size: 13px; color: #ec1c24; font-family: 'Roboto', sans-serif;  text-align:center;' data-error='wrong'>Não foi possível encontrar sua conta. Tente novamente.</b> </label>";}}?>
                </div><br>
                <div align="center">
                    <div class='row'>
                        <button type='submit' value="Entrar" name='btn_login' tabindex="3" class="col s12 btn btn-large waves-effect laranja">Entrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="container"> <a href="https://github.com/VinniciusGomes/Quiz-Pedagogia" target="_blank" style='font-weight: 300; color: #FFF'><i class="fa fa-github" aria-hidden="true"></i> Informações</a></div>
</div><br>
