<ul class="s6 offset-s6 listaId">
    <li class="idUser"><i class="fa fa-user-circle" aria-hidden="true"></i>
        <?php echo $_SESSION['nome'].' | ';?> </li>
    <li class="data">
        <?php echo date('d/m/Y',time());?> </li>
</ul>
<div class="container"><i class="fa fa-cog fa-spin fa-fw" style="font-size:1.64rem; color:#FFF;"></i>
    <n style="font-size:1.64rem; font-family: 'Roboto', sans-serif; color: #fff">Painel do professor</n><span class="sr-only">Loading...</span><br><br><br><br><br>
    <div class="row">
        <div class="col s3 m3">
            <div class="card withe darken-1">
                <div class="card-content white-text">
                    <div align="center"><span class="card-title" style="color: #000">Usuários</span>
                        <p style="color: #000">Crie um novo usuário ou altere a senha clicando no botão.</p>
                    </div>
                </div>
                <div class="card-action">
                    <div align="center">
                        <a href="editar-usuarios" class="waves-effect waves-light btn laranja"><i class="material-icons left">person_add</i>Cadastrar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s3 m3">
            <div class="card withe darken-1">
                <div class="card-content white-text">
                    <div align="center"><span class="card-title" style="color: #000">Cadastros</span>
                        <p style="color: #000">Visualize informações dos usuários cadastrados no sistema.</p>
                    </div>
                </div>
                <div class="card-action">
                    <div align="center">
                        <a href="listar-usuarios" class="waves-effect waves-light btn laranja"><i class="material-icons left">person</i>Editar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s3 m3">
            <div class="card withe darken-1">
                <div class="card-content white-text">
                    <div align="center"><span class="card-title" style="color: #000">Questões</span>
                        <p style="color: #000">Altere ou adicione questões clicando no botão.</p>
                    </div>
                </div>
                <div class="card-action">
                    <div align="center">
                        <a href="editar-perguntas" class="waves-effect waves-light btn laranja"><i class="material-icons left">edit</i>Adicionar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s3 m3">
            <div class="card withe darken-1">
                <div class="card-content white-text">
                    <div align="center"><span class="card-title" style="color: #000">Rank</span>
                        <p style="color: #000">Visualize o rank geral dos alunos e acompanhe os progressos.</p>
                    </div>
                </div>
                <div class="card-action">
                    <div align="center">
                        <a href="rank" class="waves-effect waves-light btn laranja"><i class="material-icons left">equalizer</i>Analisar</a>
                    </div>
                </div>
            </div>
        </div>
    </div><br><br>
    <div align="center">
        <a href="sair" class=" s12 m12 btn-floating btn-large waves-effect waves-light laranja"><i class="material-icons">exit_to_app</i></a><br>
        <p style="color: #fff">Sair</p>
    </div>
</div>
